# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "We all pay.xcworkspace", scheme: "We all pay")
    upload_to_app_store(force: true, skip_binary_upload: true, skip_metadata: true)
  end
  
  lane :build do
  desc "Make new build"
  build_app(scheme: "We all pay",
            workspace: "We all pay.xcworkspace",
            include_bitcode: true)
  end
  
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "UMBN28554V",
      issuer_id: "69a6de77-3663-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./fastlane/AuthKey_UMBN28554V.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
  desc "Make and upload a new build"
  build_app(scheme: "We all pay",
            workspace: "We all pay.xcworkspace",
            include_bitcode: true)
  upload_to_app_store(api_key: api_key, skip_screenshots: true, skip_metadata: true)
  end
end
